### PR TITLE
new and recent flow-graph menu and toolbar submenus

### PR DESCRIPTION
**Pull request by glennlive**
I feel this one is a much cleaner solution.  The git repo should be cleanly pulled as well.  Both toolbar and menus now share a submenu creator class, and updates get called from ActionHandler via Main.

### CODE REVIEW

**Comment by sdh11** [comment]
Looks like it's almost ready. Just a few style fixes and the assertion fix and it should be ready to merge.

**Comment by sdh11** [comment]
Looks good.

**Comment by skoslowski** [comment]
@sdh11, thanks for reviewing this. 
@glennlive thanks for your work (and openness to your comments). One last thing would be to squash your commits down to one or two meaningful change-sets and to put "grc: " in front of their commit message. Check-out "git rebase -i" for that - I am happy to give more details (via email).

**Comment by glennlive** [comment]
commits squashed down to one, and force pushed

**Comment by skoslowski** [comment]
...with minor edits. Thanks again, @glennlive. Careful not to mix tabs and spaces in the future (tools like PyCharm highlight these for you).

**Comment by glennlive** [comment]
Thanks for the tip and edits.  I hate tabs, not quit sure how they snuck in.

**Pull request closed without merging**
