### PR TITLE
Separate blocks from OOTs and core in block library panel

### PR DESCRIPTION
**Pull request by skoslowski**
The indent here is to separate blocks and their categories by module (core or OOT). This should clean-up the block tree a little. 

Right now, we have two ways to assign categories:
- the <category> tag uses a path-like syntax: root_cat/subcat/.../category
- the block_tree.xml files use a nested XML structure to easily assign such a category path many blocks

Now, the root category is special. If it is enclosed in square brackets it designates the module name Else, (backward compat), the block is assigned to the default module name [Others]

- I have added the [Core] to the category path of all in-tree block
- initially all other (OOT) block will go into [Others].
- grc-generated hier_block go into [GRC Hier Blocks]
- all these brackets are stripped before display

This idea and motivation is from @jmcorgan. 

IMHO the in-tree categories are pretty messy by themselves and could use some clean-up (to set a good example) before we force this on all the OOT maintainers.

@sdh11 can you review the implementation, @jmcorgan please check if this satisfies all requirements.

### CODE REVIEW

**Comment by skoslowski** [comment]
I'd like to merge this soon. Did anyone look at this?

**Comment by sdh11** [comment]
Only comment is maybe change 'Others' to 'External', 'Extra' or 'Out-of-Tree'. The implementation looks fine, but it does seem a bit empty with the tree defaulting to collapsed.

**Comment by sdh11** [comment]
For the gtk3 version, it might be nice to have a separate tab for the external blocks.

**Comment by skoslowski** [comment]
good point about the collapsed tree. Core is now expanded by default.
About the name that was @jmcorgan suggestion I believe. I am open to changing that.

**Pull request closed without merging**
