### PR TITLE
Bypass/Virtual sink fix

### PR DESCRIPTION
**Pull request by sdh11**
Fixed bug where the flowgraph errors if the bypassed block is connected to a virtual sink.

### CODE REVIEW

**Comment by sdh11** [comment]
Since this feature mimics a user disabling the block and building another connection, I think it makes sense to not include the bypassed block in the generated flowgraph. Also, @jmcorgan mentioned it can cause the runtime topology check to fail.

**Comment by ckuethe** [comment]
LGTM. Fixes the problem I had.

**Comment by skoslowski** [comment]
I don't see how an unconnected block instance could do any harm right now. Since in the end it shouldn't matter anyway, I am okay with removing it.

About the virtual connections fix. I will have to look into that. 

My initial thoughts are: Currently, the whole logic is the python submodule. I don't know why. Since this feature is not specific to Python as a FG output lang, moving it to the base submodule makes sense. However, for maintainability we should either move all or leave it. (not saying that you didn't cover all of it).

**Comment by sdh11** [comment]
What is the difference between the two submodules? There seems to be a lot in the python one that should probably be integrated into the base module anyway.

**Comment by ckuethe** [comment]
Is this going to get merged before 3.7.8?

**Comment by jmcorgan** [comment]
I hope so.

**Comment by sdh11** [comment]
@skoslowski if the patch looks good to you, my vote is to just merge this and then address the submodule organization after the 3.7.8 release.

**Comment by skoslowski** [comment]
I agree, a fix should make it into the release. @jmcorgan if you are okay with it, we could declare this "quick&dirty" (using methods defined in a subclass just feels weird) and revert it afterwards. I will review and merge this branch tomorrow. 

@sdh11, the real reason for the virtual ports failing is that the resolver function looks at get_connections() which ignores the bypassed status. To prevent side effects like that, I think it is best not to mess with the graph structure at all. During design time we have to have those connections anyway. After all, this really is a generate feature. So, it would be best to move all that code out of get_enabled_connections() / get_enabled_blocks() and put into the python/TopBlockGenerator._build_python_code_from_template(). Shouldn't be much work. If you want to have this into the release, we could maybe postpone merging until Wednesday.

**Comment by jmcorgan** [comment]
Let's use the current PR, once you've declared it working.  If you think you can implement a better fix, please also do so, and we'll see how risky that is to merge once it's done.

**Comment by skoslowski** [comment]
Sounds good. Since this is Seth's code originally I will him work on this if he want's to. Else, I am happy to move the code over myself.

**Comment by jmcorgan** [comment]
Up to you.

**Comment by sdh11** [comment]
@skoslowski, I see what you're saying. I'll try and move stuff over to the generator functions.

**Comment by ckuethe** [comment]
nopblock grc

Yay. This works.

**Comment by skoslowski** [comment]
Works here two. Great work, Seth. 
Squashed and pushed to master_grcwg. @jmcorgan, ready to merge.

**Comment by mbr0wn** [comment]
> I don't see how an unconnected block instance could do any harm right now. Since in the end it shouldn't matter anyway, I am okay with removing it.

Just a comment on this, for future reference, an unconnected (but instantiated) block could be harmful and/or annoying. Imagine the case where you're developing an RFNoC flow graph. You want to simply test all the other blocks for sanity or whatever, excluding the RFNoC block. You *don't* want that block's constructor to run if it's ignored/bypassed, because that'll spin up a UHD session, and maybe you don't even have hardware connected. It looks like you've opted for not instantiating unconnected blocks, which would solve this issue and I believe is the right way to do it.

**Comment by jmcorgan** [comment]
To be accurate, my original statement, that instantiated but unconnected blocks could make the topology check fail, was incorrect.  The GNU Radio scheduler will prune (but not uninstantiate) unconnected blocks during the flattening of the flowgraph before doing the final topology check.  Any unconnected blocks will not have their check_topology() method called.

However, what @mbr0wn says above is still completely valid, and for that reason alone the current way is correct.

**Comment by skoslowski** [comment]
@mbr0wn, I see your point. Although, what you describe this sounds like gr.block.start().
Anyway, I am glad you brought this up again, because that did not make it in Seth refactored version. 

@jmcorgan, you can pull a fix from master_grcwg.

**Comment by mbr0wn** [comment]
`start()` and the constructor are different things. E.g. in UHD blocks, the constructor is (rightly so) the one who instantiates the UHD session. `start()` will initiate streaming.

**Pull request closed without merging**
