### PR TITLE
Embedded Python Blocks

### PR DESCRIPTION
**Pull request by skoslowski**
The first thing I tried to do in GRC were embedding python block in flowgraphs. Finally I got it done...

This adds a new block wrapper "Embedded Python Block" to GRC which has its name, params and ports dynamically set by evaluating the source code of a regular GR python block. Its source code is embedded in the flowgraph. In the GUI the code is viewed and edited in an external, user-defined editor in form of a temp file. The block wrapper (and the GUI in general) is updated on file-changes.

In the generated code each python block get its own source file from which the main file imports.

### CODE REVIEW

**Comment by sdh11** [comment]
I think this would be a very useful feature. Right away, there are a couple of small things that could make this more user-friendly:

1. Opening the OS's default editor for python or text files rather than requiring the user to select the binary
2. Supporting different port types through the up/down arrows.

**Comment by sdh11** [comment]
As far as the dynamic evaluation, it is really slick, but I am not sold that it is the best method for building a block, especially for new users. I think we need to keep as much of the block design in a UI as possible. First, it's a closer match to the workflow of other blocks, such as changing the data type and number of input/output ports. Second, it reduces the need for users to worry about the right syntax and code structure and focus more on the actual functionality. 

I think having a new block design dialog would be a good solution (similar to the filter design tool). There could be a design panel on the left with all the options for input/output ports, types, names, parameters, default values, etc., and a preview panel on the right showing the generated code and an edit button. Since I do think the dynamic evaluation is really slick, there could also be a 'Generate Dynamically' option that partially disables the design panel but still shows all the options. 
[block-designer.pdf](https://github.com/gnuradio/gnuradio-wg-grc/files/10302/block-designer.pdf)

**Comment by skoslowski** [comment]
First comment:

1. Do you know a reliable way to go about this? I tried xdg-* but I am not sure how well that would work on different OSes. 

2. I don't want to fiddle with the externally-opened source code from GRC for now. It involves ugly research and replace and you don't know if the external editor notices the changes from GRC or just overrides them on the next save.

Second comment:

I didn't really have new users as the sole focus of this feature. Rather a quick why to prototype custom blocks or something like that. IMO this can still be useful to new users - maybe get used to the gnu radio boilder-plate in GRC and eventually graduate to writing standalone C++ blocks. 

What you are suggesting is a nice GUI for modtool add. In GRC you have to make sure, that the GUI and the source code are in sync. Both can be edited. For now, I don't want the manipulate the source code from GRC. Let's get some experience with the external editor stuff first.

I do already have a "Simple Embedded Python Block" in the works that allows configuration of the IO via the GUI and needs only work and message handlers as source code. That would be pretty close to your suggestion. This is going to be a separate feature (building on the infrastructure added here of course). Details will follow.

**Comment by skoslowski** [comment]
closing and reopening this (GitHub won't update the base branch)

**Comment by sdh11** [comment]
Did something get corrupted with rebasing this on the latest master? I've tested this on Ubuntu and OS X and I think there is an issue with the parser. GRC isn't showing any connections or even parameters for the embedded block.

**Comment by skoslowski** [comment]
Still working fine on my end. If ports and params don't show with the default source code, you probably forgot to apply the patch to gateway.py on your system

**Comment by sdh11** [comment]
That was it.

**Comment by skoslowski** [comment]
Remove those print line. Ready to remove the "hold"?

**Comment by sdh11** [comment]
I'm good with it. I do think in a future version we may want to try and automatically open the file rather than having the user select the editor. Or at least give them an option to automatically open the default editor the first time they use the block.

I found this, but it's a bit messy to support different platforms:
```
import subprocess, os
if sys.platform.startswith('darwin'):
    subprocess.call(('open', filepath))
elif os.name == 'nt':
    os.startfile(filepath)
elif os.name == 'posix':
    subprocess.call(('xdg-open', filepath))
```

**Comment by skoslowski** [comment]
Saw that code fragment before. An option to optionally auto-choose the default editor sounds good. Lets add that with a separate PR. Would you like to implement this?

**Comment by sdh11** [comment]
Sure. I'll open a new PR once this is merged.

**Pull request closed without merging**
