### PR TITLE
GRC: Defer check for GTK initialization

### PR DESCRIPTION
**Pull request by ckuethe**
Allows "--help" and "--version" to work without $DISPLAY being set.

### CODE REVIEW

**Comment by ckuethe** [comment]
OK, with these two commits, you can now invoke gnuradio-companion and get useful diagnostics whether or not DISPLAY and/or PYTHONPATH are set.

**Comment by skoslowski** [comment]
Like it. Thanks. 
Since I just recently clean this file up and with every patch it seems get more "tangled" again, I took the liberty and refactored your code a bit. See https://github.com/skoslowski/gnuradio-wg-grc/commit/3a151444c0fb32644a10e9db91d8c40f48e15e33. If that still works for you I will merge it tonight.

**Comment by jmcorgan** [comment]
I'm a little wary of merging this so close to the 3.7.8 release.

**Comment by skoslowski** [comment]
No problem. We'll just do it after.

**Comment by ckuethe** [comment]
No need to merge it this late - it was just something I noticed along the way to doing something else.

**Comment by skoslowski** [comment]
(merged)

**Pull request closed without merging**
