### PR TITLE
Variable Panel (Refactored)

### PR DESCRIPTION
**Pull request by sdh11**
Added the variable editor panel and options to hide all variables. The editor will automatically open if variables are hidden. Double clicking on GUI widgets (or variables with errors) will open the properties dialog. Variables can also be searched, added and removed from the panel.

### CODE REVIEW

**Comment by glennlive** [comment]
Seth, I've been wanting this for some time... thanks!

The first time I ran it I got these errors (when adding/deleting variables via the PropsDialog):

```
PropsDialog.py:259: GtkWarning: Unknown tag `b'
  buffer.insert_with_tags_by_name(buffer.get_end_iter(), header, 'b')
```

However, I haven't seen it since the initial run.  I didn't dig into it enough to know why.  Any ideas?

**Comment by sdh11** [comment]
I have no idea what is causing this. It showed up one time, but I haven't seen it since.

**Comment by skoslowski** [comment]
I started reviewing this. Huge change-set with some loose ends (artifacts from squashing I presume).
So, I have been going through the code and picking-out stuff that is good fro now and cleaning-up here and there. This is the result for now. I will continue later:

https://github.com/skoslowski/gnuradio-wg-grc/tree/variable_panel

The last commit on there "wip" contains only code for the new panel. I also refactored that update callback. Please have a look at the diff to your version.

**Comment by glennlive** [comment]
@sdh11 : I have added the context menu back in to my branch here:

https://github.com/glennlive/gnuradio-wg-grc/tree/variable_panel_rebase

It should contain your latest changes merged in as well, but you should probably double check.  I removed the menu from the global actions as you requested, and now it is contained completely in VariableEditor.py.  I'm not sure it really should be its own class, but that was carry over from the other menus being derived classes.  I suppose it is really preference, and so your feedback is welcome.

As to functionality as a whole I've noted to annoying gui issues:
1. Console and block tree panels no longer resize out of the way when hidden.
2. Resizing the variable-editor column widths only works correctly when the width is expanding... otherwise, it leaves the + and x icons off the screen when making it smaller again (even if it should really resize the columns and they all could fit).  They are also  hidden when the height is resized and the vertical scroll bar effectively reduces the visible column width.  Again, obviously there has to be a minimum width or things will be hidden, but this is seen even with a rather large variableEditor panel that is being resized.

**Comment by sdh11** [comment]
I think all of the resizing issues have been resolved. I think this is ready to go.

**Comment by skoslowski** [comment]
So, I tried this. Same routine as last time. This is what came up:

I found these issues/oddities:
- (Double) click on "Open Properties" is not working
- (might be related) double clicks move focus to root ("Imports")
- if I enter (by accident) an invalid expr into the value field, it shows the "Open... " field instead of the var.

Here are some open questions:
- IMO "Show Variable Editor in the Sidebar" gives the wrong idea. We use the expr. "Show.." to toggle the visibility of widgets. So maybe relabel that action as "Put ... in Sidebar" or sth.
- the integrated search bar shadows the Ctrl-F binding we have elsewhere. If we actually want to search in the vars list (weak -1 from me), we should add a binding for '/' as well, for consistency.
- I am still against the confirm dialog on delete. Why is this better than a simple undo?

Possible (future) Improvements:
- include Parameter blocks
- add default text to empty items: like  "python import statement here", "enter variable value" in light gray color.

**Comment by glennlive** [comment]
On May 18, 2016 8:20 AM, Sebastian Koslowski <notifications@github.com> wrote:
> I am still against the confirm dialog on delete. Why is this better than a simple undo?

The confirm delete menu was me, not Seth. If you dont like it kill it.  My experience was that it was so easy to delete things that I might not have realized I deleted it before I continued editing things.  So an Undo might not catch it in time.  The submenu delete is right near your mouse, so you don't have to go finding a dialog somewhere.  Just click-and-confirm-click.  If you haven't used this method before, I suppose it is a bit different.

In the main flowgraph you have to select the block (one click) and then press delete (second click).  Here, you might be trying to just select the row and bam, it disappears and makes your flowgraph un-runnable.

Just my perspective...

**Comment by skoslowski** [comment]
I can see your point. Your example is a general undo/redo limitation, though. 

This really is a matter of opinion. So, unless anyelse would like to weigh in, it comes down to @sdh11's vote =)

**Comment by glennlive** [comment]
> I can see your point. Your example is a general undo/redo limitation, though.

Yes, and I have other ideas about the undo as well (like it should maintain/restore the selected blocks), but I guess I have never accidentally deleted a block, so the undo limitation there didn't bother me.  That said, I have accidentally deleted connections before when attempting to drag select blocks.  Hmm. Maybe we need a context pop-up menu confirm delete there too.  :)

> This really is a matter of opinion.

How about another preference option?  Then you don't have to have it bug you, and I don't go randomly select-deleting things.  I would agree with you to some point... A dialog box confirm is too painful.  I'd rather just undo vs find another OK button.

> So, unless anyelse would like to weigh in, it comes down to @sdh11's vote =)

I'm not sure my vote counts as a full vote yet, but thank you for the inclusion!

**Comment by skoslowski** [comment]
True, accidental deletes of blocks/connections are not "protected". That actually an argument against the confirm dialog - consistency. 

Sure, if we keep the confirmation, we can add preference. At this point I feel we need a preferences dialog is required though, This will be a gtk3 feat, though.

**Comment by glennlive** [comment]
> True, accidental deletes of blocks/connections are not "protected". That actually an argument against the confirm dialog - consistency.

Or a new pop-up.  :)

> Sure, if we keep the confirmation, we can add preference.

It could be a hidden (no GUI) preference in the config file.

> At this point I feel we need a preferences dialog is required though, This will be a gtk3 feat, though.

I have been feeling that ever since the qt select theme.  That feature really isn't a tool, it's a preference.  Do we have a roadmap of gtk3 features?

**Comment by skoslowski** [comment]
I agree. I have a list for myself. First we have to get gtk3 going... (any help appreciated)

**Comment by sdh11** [comment]
@skoslowski:
- Fixed issue with double-click not opening properties. (May have also fixed the jump to root)
- Errors no longer cause an "Open Properties", but are shown as tooltips.
- Variables with no errors show evaluated expression
- Changed action to "Move variable editor to sidebar"
- Blank import blocks show "import ..." in light grey. Currently, variables always default to a value of 0. Considering this could be a legitimate value, I'm trying to look at modifying this in the core.

As for the other issues, I'm not quite sure what you are referring to with the integrate search. Ctrl-F still jumps to the block search for me. The search is only activated when the editor has focus and you start typing. (Unless a block is selected and 'e/d' is pressed and the block is 'disabled/bypassed/enabled').

From using it some more, I like the confirm delete context menu. Since it is right there, it shouldn't interrupt a user's workflow. I can go ahead and add another preference to disable it from grc.conf.

**Comment by sdh11** [comment]
Assuming I fixed everything, this should be ready to go.

**Comment by skoslowski** [comment]
First of all, thanks Seth for fixing these issues quickly:
- open properties is now working ✔
- the double click on unselected rows still moves focus to root item seems to be GTK ➔ maybe make it a null action (handle it w/o doing anything)?
- invalid values show correctly, tooltip is very helpful ✔

concerning my earlier open questions:
- I like 'Move....' and the setting ➔ as long as we require a restart I think it should be always sensitive.
- the Crtl-F (or keyboard bindings in general) has always been a bit weird, but with our hotkeys like e, d  ➔ I leaning towards disabling the search (same as in the block tree), but I am don't mind keeping it if you guys want it. I do think we should enable '/' to start the block search in either case (see code in block tree window)
- okay, the confirm dialog stays ✔

new issues/suggestions:
- we could make the Open Properties a grayish color to distinguish it better from values 
- re-sizing the ID column moves the symbols out of the visible area
- if I move the editor to the sidebar it never shows the block tree and the editor at the same time. It a bit cumbersome to first hide one and then show the other. ➔ I think we should have the same behavior as in the bottom panel - if both are visible show them in a vstack.

**Comment by skoslowski** [comment]
finally...merged

**Pull request closed without merging**
