### PR TITLE
Docstring extraction rewrite

### PR DESCRIPTION
**Pull request by skoslowski**
copy of #22

### CODE REVIEW

**Comment by sdh11** [comment]
This has a bug in OS X. It seems to fail handling an exception. Trying to track down the error now.

**Comment by skoslowski** [comment]
Just like I thought. Thanks for checking. Let me know if I can help track this down.

**Comment by sdh11** [comment]
The problem appears to be that the subprocess will not finish executing until the parent process is closing.

**Comment by sdh11** [comment]
New GRC tagline "Have you checked buffering?"

**Pull request closed without merging**
