### PR TITLE
grc: replace templated xml files with search and replace for qt4

### PR DESCRIPTION
**Pull request by skoslowski**
This replaces the cmake configure_file with a simple search and replace macro.
This way we 
- can still load block xmls from the source tree. 
- make qt5 the clear default with qt4 being a fallback only. 
- only need to edit some cmake when we kick out qt4 for good.

I am no cmake expert, so somebody please look that over.
I suggest to do the same for gr-qtgui/grc/*

### CODE REVIEW

**Comment by jmcorgan** [comment]
This looks way too easy :+1:

**Comment by skoslowski** [comment]
applied the same to gr-qtgui. 
Maybe @pcercuei should look over this as well.

**Comment by jmcorgan** [comment]
Basic sanity tests pass with Ubuntu 16.04 (QT 5.5.1) and  Ubuntu 14.04 (QT 4.8.5) :+1:

**Comment by jmcorgan** [comment]
One useful addition to this (unrelated to the original point of this PR, and not implemented in the existing code base) would be to autodetect the QT4 or QT5 installation.

**Comment by skoslowski** [comment]
Useful, yes. I like the idea of explicitly switching, though. As a reminder, that qt5 is our default. =)

**Comment by pcercuei** [comment]
Looks OK to me. Ship it!

**Comment by jmcorgan** [comment]
Regarding autodetect, I suggested that because it would eliminate the need for the user to pass -DDESIRED_QT_VERSION=4 when using older distros that only have QT4.  I'd rather have that than an error message that says QT5 not found.

**Comment by jmcorgan** [comment]
I'm happy to merge this into next as-is, and the autodetect can be in another PR.

**Comment by skoslowski** [comment]
Sure, I was gonna test if for qt4, so when there actually are generated files, these will get updated on make. I suspect not. (but then came that GSL bug in the way)

**Pull request merged**
