### PR TITLE
Improved block searching

### PR DESCRIPTION
**Pull request by sdh11**
Searching for blocks in the tree now matches against individual words in the search string rather than the entire string. Example: "qt freq" returns a valid match now.

Added a <tags> element to the block dtd with a couple of examples. The block tags and category are also included in the search, and final results are sorted by category.

### CODE REVIEW

**Comment by skoslowski** [comment]
Nice one. I have some simplifications to your implementation. See https://github.com/skoslowski/gnuradio-wg-grc/commit/e1871f7f50e9c01054b9b7d3c2f02e7916631beb.

About the search algorithm itself: This implements a implicit AND between words which works fine and can be merged like this.

But while your at it: Shouldn't we maybe add an OR fallback to this? Better yet, we could add a search score which is used for sorting and then increase the score with every hit for each key.

**Comment by sdh11** [comment]
Squashed all your changes. Looks much better. Thanks.

What do you think should contribute to a search score?

**Comment by sdh11** [comment]
I've added an example sorting method based on the frequency of the keywords in the searchable strings: https://github.com/sdh11/gnuradio-wg-grc/tree/frequency_sort

I don't currently like this implementation, because I had to remove the block categories in order to get everything to sort correctly. When the block categories are included in the tree, all the items are sorted  with respect to the other elements under the same category and not sorted overall.

**Comment by skoslowski** [comment]
Looks good now. Unfortunately I can't merge this without the sorting part. Example: when I search for  Variable, I don't get want I want in the top results.

I don't think keyword freq is the right approach here. We should instead prioritize matches from the block name over that from tags, cat, key. And then matches at the start of a keyword over those in the middle. When you know a block name, you want that to come up at the top.

How about you sort the categories based to the highest scored match under it.

**Comment by sdh11** [comment]
Sounds good. I didn't really life the frequency approach either; that was just a first stab. I'll try and see if I can get the categories to sort correctly.

**Comment by skoslowski** [comment]
Any update on this?

**Comment by skoslowski** [comment]
closing this for now. We'll revisit this after the gtk3 switch.

**Comment by sdh11** [comment]
Sounds good. That was my plan anyway.

**Pull request closed without merging**
