### PR TITLE
Default editor for embedded python blocks

### PR DESCRIPTION
**Pull request by sdh11**
This gives the user the option to open embedded python blocks with the system's default editor.

### CODE REVIEW

**Comment by skoslowski** [comment]
Thanks for implementing this so quickly. Really improves usability. Minor bug: external_editor is missing a "import gtk"

Code structure
I think I would be better to consolidate both, the editor selection dialog and the logic to choose the default editor into a single "flow" function residing in Dialogs.py. Its output should be the editor filepath which we can install in the ExternalEditor class (e.g. via a class attribute). Reasoning:
- all of the code is in one place - together with the other dialogs. 
- external_editor.py stays nice an tidy (no gtk dialog code)
- we really only need to find the editor filepath once, not each time a editor is opened. So, the editor flow can return early if it was called before. Once, per GRC instance, we figure out the platform specific default editor filepath, if required.
- the magic value to use the default editor should be something unambiguous (e.g. "#default")

**Comment by sdh11** [comment]
Ok, I pushed a reorganized version with the dialogs in Dialogs.py. 

The `open_editor()` function in `ExternalEditor` still needs to check if default is selected every time. This is because it uses the `xdg-open` and `open` processes in order to trigger the OS default editor and it never actually knows what editor is being used.

**Comment by sdh11** [comment]
One of the other thoughts that I had was that the `ExternalEditor` class should throw an exception if it is unable to open a selected path or the default editor. Then we could relaunch the dialog to choose the correct editor. Right now, I just have the `open_editor()` function setting the constant to '#none' before aborting, which forces the user to select again when they try to open the editor.

**Comment by skoslowski** [comment]
I like that idea with the exception. I still think the ```ExternalEditor``` should not have to decide what OS its run on each time an editor is opened, ```open``` and ```xdg-open``` are just like any other editor executables. I'd prefer to move this to your dialogs flow and have it set the executable in ```ExternalEditor``` (class var) as a result. This way we have a strict separation of responsibilities between the GUI part and the business logic for the editor. Also, setting and handling of the magic value are all in one location.

**Comment by sdh11** [comment]
Fixed and rebased on master_grcwg. Should be ready to go.

**Comment by skoslowski** [comment]
Thanks. Looks good. I made a few more adjustments. See if those are okay for you https://github.com/skoslowski/gnuradio-wg-grc/tree/default_editor

**Comment by sdh11** [comment]
Looks good.

**Pull request closed without merging**
