### PR TITLE
Custom Code Blocks

### PR DESCRIPTION
**Pull request by skoslowski**
This adds a new block that allows to enter arbitrary python code which is inserted between the imports and the top/hier_block class in the generated code. Consequently, this code can be accessed/used by other variables/blocks. Variables, however, can not be used inside the custom code (too much magic).
It builds on the ability to enter multi-line python code with an external editor introduced with embedded python blocks.

@trondeau, is this what you had in mind (Dev Call Oct)

### CODE REVIEW

**Comment by trondeau** [comment]
Conceptually, yes, this is what I was thinking. I went some way down this path myself a while ago, but I also ran into the variable problem. I'm worried that people might also run into this problem, expecting to be able to use a variable declared elsewhere in the app.

Would there be any way to pass variables as arguments to the function?

**Comment by skoslowski** [comment]
Yes, that is the indented use. 

If we were to allow variables to be used inside custom code we have to put it in the __init__ function later with is somewhat awkward if its more than a helper function.

I was gonna add some documentation anyway, but this particular part could be added as a comment in the custom code parameters default value

**Comment by trondeau** [comment]
Thanks, that sounds good. I'll try to play with this sometime soon to actually check it out. I just want to make sure it's operation and limitations are easy to understand, documented, and hopefully have useful error messages.

**Comment by trondeau** [comment]
Sebastian,
Ok, this is great. It wasn't particularly obvious how it was supposed to work, though it makes sense in many ways once I got it to work. Like I tried to just have it print the args passed to the function without returning anything. The custom code block was fine, but I couldn't use it anywhere this way.

Also, maybe we can link together the name of the Custom Code block ID and the function in the code? Then make another line that takes in the arguments. The code block itself should get populated with this information up top, and the user then fills in the body of the function.

Of course, this would be more like a "Custom Function" block than "Custom Code". One issue I'm thinking about in the use case is that I've defined a function with some arguments to it, but I can't recall them, so I have to open up the Custom Code block, then click to open the editor, and use that to remember what I'm doing in the GRC flowgraph.

Another thing I'd like to see is the Generated Code tab show the code.

Does all this make sense or do you need more info?

Generally speaking, this is a great step in the right direction and something I think will be very useful.

**Comment by skoslowski** [comment]
Thanks for the feedback. My intention was to not limit this to functions only. Currently, you can define consts, imports, other functions, etc. in there. I am not sure if this is necessarily wise, though.

Functionally this adds nothing new whatsoever - put all "custom code" in a python module next to grc file and drop an import block in the flowgraph and we have the exact same thing. Putting it in a block simply adds convenience (and keep everything in a single file).

I think, I will rename this to Python Module to make the intend clearer and put all generated Code in a separate file $id.py which will then be imported in the main file (at runtime). $id here is the block id of the custom code. 

In this scenario I'd prefer to "import $id" instead of "from $id import *", which means, functions, consts will have to accessed via $id.my_custom_function(...). "Namespaces are one honking great idea -- let's do more of those!" Also, we would retain the concept of every object in the namespace has a block representation (except for imports).

Now, the alternative would be to only import (and therefore allow usage of) a single callable from such a module. This would effectively result in the MATLAB-style of modules. From outside a module you can only access a single function - if there a multiple in there it will pick the one with the same name as the module (python: from $id import $id). If there is no such function it will pick the first one (python: a random callable - the objects in a module are not ordered). 

This is certainly do-able, but except from the simpler usage ($id(...) instead of $id.my_function(...) there isn't much gain...

**Comment by skoslowski** [comment]
I get the idea of having a parameter to set function args and therefore alter the "source code". @sdh11  and I discussed this for the embedded python blocks interface. My concern however is the fact, that it is very hard to keep both the editor and parameter values in sync: Once an editor is launched you can't guarantee that the user will accept a reload of the (temp) file in his editor if he changes a parameter that results in a source code update (like args to a function). If he doesn't GUI and code are out-of-sync. For now, I'd rather have only an initial (default) value, but don't alter user provided code afterwards.

**Comment by jmcorgan** [comment]
I completely agree about the 'import $id' and separate $id.py file.

**Comment by skoslowski** [comment]
done

**Comment by trondeau** [comment]
@skoslowski I'm on board with everything you said here. I think it makes it all a bit more understandable and robust.

And I was definitely thinking about the problem of the function call in the GRC block getting out of sync with the code once the editor is opened. Even still, I'd like some easy way to know what's inside the code within GRC that doesn't involve opening the editor directly. Perhaps if it just populates the "Generated Code" tab that would be good enough.

**Comment by skoslowski** [comment]
@trondeau, makes total sense, forgot to add it. Its in there now.

@sdh11, would you review this?

**Comment by mbr0wn** [comment]
Just sayin' this is pretty cool :)

**Comment by sdh11** [comment]
To add to what @trondeau was saying, I think it would be good to somehow have any functions in the module shown in the GUI similar to how parameters are shown. It might be too confusing for users though, since they aren't actually parameters.

I messed around with this and tried to add a rewrite function for modules (similar to embedded blocks), but couldn't get it to work. Another option I tried was adding the function definitions to the block's comments, but that looked awful.

**Comment by sdh11** [comment]
Can the python module block at least show it's ID variable in the GUI even if we don't have anything else in there? If you have multiple modules, there's no way to see which is which without opening it.

**Comment by skoslowski** [comment]
Good one. Can't believe I forgot about that. Fixed.

**Pull request merged**
