### PR TITLE
created recently opened files submenu

### PR DESCRIPTION
**Pull request by glennlive**
@skoslowski

As is, this is functional, but it isn't pretty at several points.  Please take a look and let me know where things need to be fixed.  I added the sub-menus to the toolbar as well, which I think could be quite useful, but that impacted the actions class and cross-linked the tool bar with the menu creation.

It also looks like my attempt to merge the branch brought back in my horizontal scroll wheeling, despite my attempt to reset hard back to the master repo...

### CODE REVIEW

**Comment by sdh11** [comment]
Two quick comments:
- Disable the dropdown for the toolbar and also the submenu when there are no files to show. Right now it's empty
- Can you clean up the merge commits and just have a single branch?

**Comment by sdh11** [comment]
Also please remove the horizontal mouse wheel scrolling commit. This was already merged.

**Comment by skoslowski** [comment]
Like it. The toolbar menus are great. Looking at the code, I have few suggestions
- Move the logic from prefs into a new mainwindow function that updates the list, menus and saves to prefs
- I don't really like tagging of the submenus in the actions. How about we save a dict of the submenus in the main_menu object and pass it to the toolbar init. Then replace the items in TOOLBAR_LIST with tuples (action, tag) and use these to insert the submenus when build the toolbar items

**Comment by glennlive** [comment]
These thoughts are great.  I hope to get a chance to look back at this again soon.

**Pull request closed without merging**
