### PR TITLE
Variable Editor Dialog

### PR DESCRIPTION
**Pull request by skoslowski**
This adds a new dialog to create, edit and delete variables. Works also with extended variables like QT GUI Controls. Variables block can now optionally be hidden from canvas all together.

Question: (last commit) Should variable blocks created from the dialog have fixed or random coordinates? If variable blocks are hidden, they wouldn't get scattered all over?

### CODE REVIEW

**Comment by sdh11** [comment]
For this release, it's probably best to use random coordinates and have variables shown by default, so that it's consistent with the current workflow. I'd like to get some feedback on the editor dialog before pushing it as the default way.

**Comment by sdh11** [comment]
Also, I'd like to have a single variable block or something similar whenever this becomes the main workflow for interacting with variables.

**Comment by skoslowski** [comment]
I have some code this already. It shows like as stack of blocks when vars are hidden. Maybe I can get it done before the release.

**Comment by skoslowski** [comment]
@sdh11, I pushed my current version of the "Variable Stack" block representation. Not 100% sure I like it... Give it a try and see if you like the Labels, Graphics and if the Look&Feel is okay.

Note, that it is currently anchored below the options block mostly due to implementation issues. Treading this as a normal block would result in many lines of boilerplate code and many special case if-clauses... I want to avoid that.

**Comment by sdh11** [comment]
I'm not sure how much I like this either. I've shown this to a few people with mixed responses.

From a usability perspective, the editor and the ability to hide variables is great. Many people really liked that. I dislike how the user loses some usability with the stack implementation. Mainly, I don't like the fact you cannot see what variables/imports exist in the flow graph without opening up the editor (Some people agreed and some didn't really care). If you're editing one block and forget a variable name, that could be really annoying. Another usability loss is the ability to copy variables in hidden mode.

What about the possibility of having the variable editor as a dock similar to how it is handled in Matlab? That would solve the issue of showing the variables in the main window while making it easy to edit them. Then, we wouldn't need the variable stack at all and would only show the variable editor when the variables are hidden.

**Comment by sdh11** [comment]
I'm going to mess around with that and see if I can duplicate the Matlab style of things.

**Comment by sdh11** [comment]
Here is the current version I have for a WIP: sdh11@392531c9. It has the same basic functionality as the variable editor, but as part of the main window rather than a dialog. I don't have all the functionality complete to open up other dialogs yet. I think this is a much better solution; it makes editing variables really easy and cleans up the flowgraph when everything is hidden.

**Comment by skoslowski** [comment]
@sdh11, any updates for this one?

**Comment by sdh11** [comment]
I am planning to try and get this done during the weekend.

**Comment by sdh11** [comment]
Replaced by #57.

**Pull request closed without merging**
