### PR TITLE
grc: per-flowgraph custom run commands

### PR DESCRIPTION
**Pull request by skoslowski**
This adds a param to the Options block (Tab Advanced) which lets users set their own run commands.
The default is "{python} -u {filename}" which gets expanded to the python interpreter path GRC is run from and the file path of the generated file, respectively.

Use cases: 
- running custom code through e.g. sub-classing the generated code (and running that)
- remote execution by running some script that deploys and executes the generated code

Misc:
- Is the current placeholder format (the use of {...}) the best way to go here?

### CODE REVIEW

**Comment by sdh11** [comment]
I think {...} is fine for the placeholders assuming people are familiar with python. The other possibility would be using environment variable styles `$PYTHON -u $FILENAME`

**Comment by sdh11** [comment]
Considering the fact that most people using this feature probably wrote their wrapper functions in python, I think the first way is fine.

**Comment by skoslowski** [comment]
Separating the argument parser allows easy extension of the the generated parser for custom code as well as passing custom values via the options argument in main()

**Comment by sdh11** [comment]
I think this looks good, but I suggest holding this for a bit because of the XInitThreads. I will try to look into that later today.

**Comment by skoslowski** [comment]
I have merged this. We'll discuss the XInitThreads call in a separately. Open an issue (or PR) as soon as you've looked into this

**Pull request closed without merging**
