### PR TITLE
New sub-menu with items for each generate mode

### PR DESCRIPTION
**Pull request by skoslowski**
Replace File->New with a sub-menu with items for each generate mode. Clicking File->New->No Gui open a new FG with the generate_mode preset.

Idea by @sdh11.

### CODE REVIEW

**Comment by sdh11** [comment]
What do you think about extending this idea, and limiting the GUI blocks that can be added to specific flowgraphs? I.E. only QT blocks can be added to the QT flowgraph types.

**Comment by sdh11** [comment]
But, I wouldn't want to lock down a flowgraph so that the user cannot change the GUI type at a later date.

**Comment by skoslowski** [comment]
We already check GUI blocks against the generate mode during validation. Enforcing this feels rather restrictive than actually helpful.

**Comment by sdh11** [comment]
I was thinking more from a new user perspective; the only blocks available are based on the type of flowgraph you pick. But, I can see it being restrictive for someone who has multiple GUI blocks for testing but uses it headless in production.

**Comment by sdh11** [comment]
Looks good.

**Pull request closed without merging**
